In [4]:
import numpy as np

In [5]:
list =[1,2,3]
np.array(list)

array([1, 2, 3])

In [8]:
matriz = [[1,2,3],[4,5,6],[7,8,9]]
np.array(matriz)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [10]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [11]:
np.arange(0,10,2)

array([0, 2, 4, 6, 8])

In [12]:
np.linspace(0,10,3)

array([ 0.,  5., 10.])

In [16]:
np.zeros((10,10))

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [17]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [20]:
np.random.rand(4,4)


array([[0.44450909, 0.12109979, 0.51740769, 0.34414294],
       [0.39963225, 0.08001967, 0.56455515, 0.72838914],
       [0.26695662, 0.87225063, 0.06517422, 0.63250786],
       [0.83469676, 0.38908105, 0.4745894 , 0.0829972 ]])

In [22]:
np.random.randn(4,4)

array([[-0.36492472,  0.47788405,  2.39389408, -1.21740192],
       [-0.09747204,  1.86914852, -1.33673801,  0.45148109],
       [ 0.70625384,  0.76785242,  0.3282016 ,  2.43481797],
       [ 1.33509403,  0.03863924, -0.68980552, -0.72869019]])

In [30]:
np.random.randint(0,10,(10,10))

array([[7, 2, 3, 4, 9, 9, 6, 0, 4, 3],
       [3, 5, 3, 2, 6, 0, 7, 1, 2, 5],
       [4, 5, 2, 7, 3, 0, 3, 9, 0, 2],
       [5, 7, 4, 8, 9, 9, 2, 1, 5, 7],
       [4, 6, 0, 5, 1, 6, 8, 1, 4, 0],
       [5, 1, 6, 5, 4, 1, 4, 4, 1, 9],
       [5, 0, 4, 6, 1, 4, 7, 3, 1, 1],
       [0, 8, 2, 2, 9, 6, 8, 7, 8, 9],
       [7, 9, 8, 9, 2, 3, 9, 8, 7, 8],
       [5, 8, 4, 7, 2, 9, 5, 5, 8, 3]])

In [39]:
arr = np.arange(25)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [40]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [47]:
arr.max()


24

In [48]:
arr.min()

0

In [49]:
arr.argmax()

24

In [50]:
arr.dtype


dtype('int64')

Operações matematicas

In [59]:
arr = np.arange(1,10)


In [60]:
arr + arr

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18])

In [61]:
arr * arr

array([ 1,  4,  9, 16, 25, 36, 49, 64, 81])

In [62]:
arr ** 3

array([  1,   8,  27,  64, 125, 216, 343, 512, 729])

In [63]:
np.sqrt(arr)

array([1.        , 1.41421356, 1.73205081, 2.        , 2.23606798,
       2.44948974, 2.64575131, 2.82842712, 3.        ])

In [65]:
np.exp(arr)

array([2.71828183e+00, 7.38905610e+00, 2.00855369e+01, 5.45981500e+01,
       1.48413159e+02, 4.03428793e+02, 1.09663316e+03, 2.98095799e+03,
       8.10308393e+03])

In [66]:
np.sin(arr)

array([ 0.84147098,  0.90929743,  0.14112001, -0.7568025 , -0.95892427,
       -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849])

In [67]:
np.cos(arr)

array([ 0.54030231, -0.41614684, -0.9899925 , -0.65364362,  0.28366219,
        0.96017029,  0.75390225, -0.14550003, -0.91113026])

In [68]:
np.log(arr)

array([0.        , 0.69314718, 1.09861229, 1.38629436, 1.60943791,
       1.79175947, 1.94591015, 2.07944154, 2.19722458])

In [81]:
arr.reshape(3,3)
arr


array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [82]:
arr * arr

array([[ 1,  4,  9],
       [16, 25, 36],
       [49, 64, 81]])

In [83]:
np.dot(arr,arr)

array([[ 30,  36,  42],
       [ 66,  81,  96],
       [102, 126, 150]])

In [85]:
arr.sum(axis=0)

array([ 6, 15, 24])

# Indexacao

In [94]:
arr = np.arange(1,10)
arr

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [95]:
arr[-1]

9

In [96]:
arr[0:3]

array([1, 2, 3])

In [98]:
matriz = arr.reshape(3,3)
matriz

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [100]:
matriz[0]

array([1, 2, 3])

In [106]:
matriz[:]

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [115]:
matriz[:,1]

array([2, 5, 8])

In [117]:
arr[:4] = 100
arr

array([100, 100, 100, 100,   5,   6,   7,   8,   9])

array([[100, 100, 100],
       [100,   5,   6],
       [  7,   8,   9]])

In [122]:
arr = np.arange(1,10)

arr > 5

array([False, False, False, False, False,  True,  True,  True,  True])

In [124]:
arr[arr < 5]

array([1, 2, 3, 4])