# Classificador Rede Neural.

Exemplo de um classificador usando o toy dataset iris do framework scikit learn, com uma rede neural construindo a partir do framework Keras. 

## 1 - Carregando dataset.

In [1]:
from sklearn.datasets import load_iris

iris = load_iris()

## 2 - Dividir o Dataset em Treino e Teste.

In [12]:
from sklearn.model_selection import train_test_split

X_train, x_test, y_train, y_test = train_test_split(iris.data, iris.target, test_size = 0.25, random_state = 42)

print("Tamanho da base de treino é: ", len(X_train))
print("Tamanho da base de teste é: ", len(x_test))

# print(type(X_train))
# print(y_train[:])
# print(X_train[:,[0,2]])
print(iris.feature_names)

features = [2]

X_train = X_train[:,features]
x_test = x_test[:,features]


Tamanho da base de treino é:  112
Tamanho da base de teste é:  38
<class 'numpy.ndarray'>
['sepal length (cm)', 'sepal width (cm)', 'petal length (cm)', 'petal width (cm)']


### 2.1 - Tratar os dados.

Transformar as label do dataset em um array do tipo 
<li>[1 0 0] para 'setosa',</li> 
<li>[0 1 0] para versicolor e </li> 
<li>[0 0 1] para virginica.</li>  

In [3]:
from keras.utils import np_utils

print(iris.target_names)

y_train_encoded = np_utils.to_categorical(y_train)
y_test_encoded = np_utils.to_categorical(y_test)

print(y_train_encoded[1])

Using TensorFlow backend.


['setosa' 'versicolor' 'virginica']
[1. 0. 0.]


## 3 - Instanciar classificador.

In [4]:
from keras.models import Sequential
from keras.layers import Dense
from keras import losses

model = Sequential()
model.add(Dense(16, input_dim=len(features), activation='relu'))
model.add(Dense(3,activation='softmax'))

# losses.

model.compile(loss='categorical_crossentropy',
              optimizer='sgd',
              metrics=['accuracy'])

## 4 - Treinar classificador com os dados de treino.

In [5]:
model.fit(X_train, y_train_encoded,batch_size=16, epochs=100)

Epoch 1/100
112/112 [==============================] - 0s 2ms/step - loss: 1.6244 - acc: 0.3125
Epoch 2/100
112/112 [==============================] - 0s 138us/step - loss: 1.3593 - acc: 0.3304
Epoch 3/100
112/112 [==============================] - 0s 202us/step - loss: 1.2277 - acc: 0.3482
Epoch 4/100
112/112 [==============================] - 0s 234us/step - loss: 1.1468 - acc: 0.3482
Epoch 5/100
112/112 [==============================] - 0s 190us/step - loss: 1.0947 - acc: 0.3482
Epoch 6/100
112/112 [==============================] - 0s 161us/step - loss: 1.0697 - acc: 0.3482
Epoch 7/100
112/112 [==============================] - 0s 165us/step - loss: 1.0525 - acc: 0.3482
Epoch 8/100
112/112 [==============================] - 0s 144us/step - loss: 1.0385 - acc: 0.3482
Epoch 9/100
112/112 [==============================] - 0s 150us/step - loss: 1.0294 - acc: 0.2054
Epoch 10/100
112/112 [==============================] - 0s 166us/step - loss: 1.0219 - acc: 0.2679
Epoch 11/100
112/112 

112/112 [==============================] - 0s 127us/step - loss: 0.7826 - acc: 0.6518
Epoch 84/100
112/112 [==============================] - 0s 151us/step - loss: 0.7777 - acc: 0.6518
Epoch 85/100
112/112 [==============================] - 0s 147us/step - loss: 0.7758 - acc: 0.6518
Epoch 86/100
112/112 [==============================] - 0s 194us/step - loss: 0.7717 - acc: 0.6518
Epoch 87/100
112/112 [==============================] - 0s 125us/step - loss: 0.7692 - acc: 0.6518
Epoch 88/100
112/112 [==============================] - 0s 95us/step - loss: 0.7678 - acc: 0.6518
Epoch 89/100
112/112 [==============================] - 0s 119us/step - loss: 0.7645 - acc: 0.6518
Epoch 90/100
112/112 [==============================] - 0s 133us/step - loss: 0.7611 - acc: 0.6518
Epoch 91/100
112/112 [==============================] - 0s 198us/step - loss: 0.7573 - acc: 0.6607
Epoch 92/100
112/112 [==============================] - 0s 99us/step - loss: 0.7553 - acc: 0.6518
Epoch 93/100
112/112 [===

## 5 - Extrair métrica


In [6]:
def evaluate(model, X, y):
    return model.evaluate(X, y)

score = evaluate(model, X_train, y_train_encoded)
score_teste = evaluate(model, x_test, y_test_encoded)

print('Acurracia dos dados treino: ',score)
print('Acurracia dos dados teste: ',score_teste)

print(y_test[:])
predict = model.predict_classes(x_test)
print(predict)

38/38 [==============================] - 0s 61us/step
Acurracia dos dados treino:  [0.7299906781741551, 0.6607142857142857]
Acurracia dos dados teste:  [0.7183860728615209, 0.7105263189265603]
[1 0 2 1 1 0 1 2 1 1 2 0 0 0 0 1 2 1 1 2 0 2 0 2 2 2 2 2 0 0 0 0 1 0 0 2 1
 0]
[2 0 2 2 2 0 2 2 2 2 2 0 0 0 0 2 2 2 2 2 0 2 0 2 2 2 2 2 0 0 0 0 2 0 0 2 2
 0]


In [7]:
from sklearn import metrics
print(metrics.classification_report(y_test, predict, target_names=iris.target_names))
print(metrics.confusion_matrix(y_test, predict))

              precision    recall  f1-score   support

      setosa       1.00      1.00      1.00        15
  versicolor       0.00      0.00      0.00        11
   virginica       0.52      1.00      0.69        12

   micro avg       0.71      0.71      0.71        38
   macro avg       0.51      0.67      0.56        38
weighted avg       0.56      0.71      0.61        38

[[15  0  0]
 [ 0  0 11]
 [ 0  0 12]]


/usr/local/lib/python3.5/dist-packages/sklearn/metrics/classification.py:1143: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)


In [8]:
from sklearn.model_selection import KFold

kf = KFold(n_splits=2)
X  = iris.data
y = iris.target
kf.get_n_splits(X)

# print(kf)  

for train_index, test_index in kf.split(X):
   print("TRAIN:", train_index, "TEST:", test_index)
   X_train, X_test = X[train_index], X[test_index]
   y_train, y_test = y[train_index], y[test_index]




TRAIN: [ 75  76  77  78  79  80  81  82  83  84  85  86  87  88  89  90  91  92
  93  94  95  96  97  98  99 100 101 102 103 104 105 106 107 108 109 110
 111 112 113 114 115 116 117 118 119 120 121 122 123 124 125 126 127 128
 129 130 131 132 133 134 135 136 137 138 139 140 141 142 143 144 145 146
 147 148 149] TEST: [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71
 72 73 74]
TRAIN: [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71
 72 73 74] TEST: [ 75  76  77  78  79  80  81  82  83  84  85  86  87  88  89  90  91  92
  93  94  95  96  97  98  99 100 101 102 103 104 105 106 107 108 109 110
 111 112 113 114 115 116 117 118 119 120 121 122 123 124 125 1