## Exercícios NumPy  


In [1]:
import numpy as np

### Criação de matrizes

<b>Crie um vetor com 10 zeros</b>

In [43]:
arr = np.zeros(10)
arr

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

<b>Crie um vetor com 10 uns</b>

In [44]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

<b>Crie uma matriz 10x10 de valores zeros</b>

In [11]:
np.zeros((10,10))

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

<b>Crie uma matriz 3x3 de 0 até 8</b>

In [15]:
arr = np.arange(0,9)
arr.reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

<b>Crie uma matriz identidade 3x3</b>

In [41]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

<b>Crie uma matrix 5x5 com valores randômicos</b>

In [16]:
np.random.randint(0,10,(5,5))

array([[4, 1, 4, 1, 5],
       [5, 6, 9, 4, 6],
       [5, 4, 7, 1, 7],
       [7, 7, 8, 4, 7],
       [0, 1, 3, 3, 3]])

<b>Crie um array dos numeros pares de 10 até 50</b>

In [20]:
np.arange(10,51,2)

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42,
       44, 46, 48, 50])

<b>Crie a seguinte matriz:</b>


array([[ 0.01,  0.02,  0.03,  0.04,  0.05,  0.06,  0.07,  0.08,  0.09,  0.1 ],
       [ 0.11,  0.12,  0.13,  0.14,  0.15,  0.16,  0.17,  0.18,  0.19,  0.2 ],
       [ 0.21,  0.22,  0.23,  0.24,  0.25,  0.26,  0.27,  0.28,  0.29,  0.3 ],
       [ 0.31,  0.32,  0.33,  0.34,  0.35,  0.36,  0.37,  0.38,  0.39,  0.4 ],
       [ 0.41,  0.42,  0.43,  0.44,  0.45,  0.46,  0.47,  0.48,  0.49,  0.5 ],
       [ 0.51,  0.52,  0.53,  0.54,  0.55,  0.56,  0.57,  0.58,  0.59,  0.6 ],
       [ 0.61,  0.62,  0.63,  0.64,  0.65,  0.66,  0.67,  0.68,  0.69,  0.7 ],
       [ 0.71,  0.72,  0.73,  0.74,  0.75,  0.76,  0.77,  0.78,  0.79,  0.8 ],
       [ 0.81,  0.82,  0.83,  0.84,  0.85,  0.86,  0.87,  0.88,  0.89,  0.9 ],
       [ 0.91,  0.92,  0.93,  0.94,  0.95,  0.96,  0.97,  0.98,  0.99,  1.  ]])

In [23]:
np.arange(0.01,1.01,0.01).reshape(10,10)


array([[0.01, 0.02, 0.03, 0.04, 0.05, 0.06, 0.07, 0.08, 0.09, 0.1 ],
       [0.11, 0.12, 0.13, 0.14, 0.15, 0.16, 0.17, 0.18, 0.19, 0.2 ],
       [0.21, 0.22, 0.23, 0.24, 0.25, 0.26, 0.27, 0.28, 0.29, 0.3 ],
       [0.31, 0.32, 0.33, 0.34, 0.35, 0.36, 0.37, 0.38, 0.39, 0.4 ],
       [0.41, 0.42, 0.43, 0.44, 0.45, 0.46, 0.47, 0.48, 0.49, 0.5 ],
       [0.51, 0.52, 0.53, 0.54, 0.55, 0.56, 0.57, 0.58, 0.59, 0.6 ],
       [0.61, 0.62, 0.63, 0.64, 0.65, 0.66, 0.67, 0.68, 0.69, 0.7 ],
       [0.71, 0.72, 0.73, 0.74, 0.75, 0.76, 0.77, 0.78, 0.79, 0.8 ],
       [0.81, 0.82, 0.83, 0.84, 0.85, 0.86, 0.87, 0.88, 0.89, 0.9 ],
       [0.91, 0.92, 0.93, 0.94, 0.95, 0.96, 0.97, 0.98, 0.99, 1.  ]])

### Indexação

In [24]:
matriz = np.arange(1,37).reshape(6,6)
matriz

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18],
       [19, 20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29, 30],
       [31, 32, 33, 34, 35, 36]])

<b>consiga a seguinte saída: </b>

array([[ 7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18],
       [19, 20, 21, 22, 23, 24]])

In [27]:
matriz[1:4]

array([[ 7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18],
       [19, 20, 21, 22, 23, 24]])

<b>acesse o valor 14: </b>

In [29]:
matriz[2,1]

14

<b>acesse apenas a coluna 3:</b>

In [36]:
matriz[:,2]

array([ 3,  9, 15, 21, 27, 33])

<b>acesse apenas a coluna 3 da linha 1 até a linha 3:</b>

In [40]:
matriz[1:4,3]

array([10, 16, 22])

<b>A partir da matriz, retorne a seguinte: </b>

array([[ 1,  2,  3,  4,  5,  6],
       [13, 14, 15, 16, 17, 18],
       [31, 32, 33, 34, 35, 36],
       [ 7,  8,  9, 10, 11, 12]])

### usando a matriz acima, faça:

<b>Obter a soma de todos</b>

In [38]:
matriz.sum()

666

<b>Obter o desvio padrão</b>

In [39]:
matriz.std()

10.388294694831615

<b>Obter a soma das colunas</b>

In [37]:
matriz.sum(axis=0)

array([ 96, 102, 108, 114, 120, 126])